steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/firebase']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['/usr/local/bin/ng', 'build', '--environment', 'test']
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      [
        '/usr/local/bin/firebase',
        'deploy',
        '--project',
        'test',
        '--token',
        '${_FIREBASE_TOKEN}',
      ]
